repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
    - id: mypy
      args: [--strict, --warn-unused-configs, --ignore-missing-imports]
      additional_dependencies:
        - pycryptodome
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear
        - flake8-pyproject
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
